name: Build

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20, 22, 23]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test

      - name: Upload coverage to Coveralls (only on Node.js 22)
        if: matrix.node-version == '22'
        uses: coverallsapp/github-action@v2
        with:
          file: coverage/lcov.info
